version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messages
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          memory: 512M

  mess:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
      - zookeeper
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: messages
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: messages
      KAFKA_GROUP_ID: message_group
    command: ["./wait-for-kafka.sh", "kafka", "./mess"]
